-- 코드를 작성해주세요
WITH AVG_T AS (
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
),
GRADE_T AS (
    SELECT EMP_NO,
    CASE 
        WHEN AVG_SCORE >= 96 THEN 'S'
        WHEN AVG_SCORE >= 90 THEN 'A'
        WHEN AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END GRADE
    FROM AVG_T
),
BONUS_T AS(
    SELECT E.EMP_NO, EMP_NAME, GRADE,
    CASE
    WHEN GRADE = 'S' THEN SAL*0.2
    WHEN GRADE = 'A' THEN SAL*0.15
    WHEN GRADE = 'B' THEN SAL*0.1
    ELSE 0
    END BONUS
    FROM GRADE_T G INNER JOIN HR_EMPLOYEES E
    ON E.EMP_NO = G.EMP_NO
)

SELECT EMP_NO, EMP_NAME, GRADE, BONUS
FROM BONUS_T
ORDER BY EMP_NO